aws-ebs-csi-driver:
  storageClasses:
    - name: ebs-sc
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      parameters:
        type: gp2

aws-load-balancer-controller:
  clusterName: argocd-demo
  region: ap-south-1  # Update to your region

external-secrets:
  env:
    AWS_REGION: ap-south-1  # Update to your region
